### ISSUE TITLE
pumpdog.me error 500

### ISSUE THREAD

**Issue by h4ck3rm1k3** [e14n/pump.io#1104] opened 2015-10-17 14:42 UTC
my account is h4ck3rm1k3@identi.ca

when I follow :
https://pumpdog.me/rsd

https://pumpdog.me/main/proxy Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pump.js:212 Error: Internal Server Error
    at Object.$.ajax.error (pump.js:638)
    at c (jquery.min.js:4)
    at Object.p.fireWith (jquery.min.js:4)
    at k (jquery.min.js:6)
    at XMLHttpRequest.r (jquery.min.js:6)
pump.js:218 Internal Server Error

chromium:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36

**Comment by larjona** [comment] 2015-11-03 18:23
Can you still reproduce this problem? Could you try to follow another pumpdog.me account, for example larjona_test@pumpdog.me? I'm not sure if this is a temporary problem, a problem related with pumpdog.me server, or related to that account... (I could follow it from my identi.ca account without problems).

**Comment by strugee** [comment] 2015-11-03 19:45
IIRC this was filed before Evan went around and restarted all the E14N servers, right? That might be it.

**Comment by h4ck3rm1k3** [comment] 2015-11-03 23:32
still happening

POST https://pumpdog.me/main/proxy 500 (Internal Server Error)send @ jquery.min.js:6x.extend.ajax @ jquery.min.js:6Pump.proxyActivity @ pump.js:622Pump.newMinorActivity @ pump.js:587Pump.PersonView.Pump.TemplateView.extend.followProfile @ view.js:1847x.event.dispatch @ jquery.min.js:5v.handle @ jquery.min.js:5
jquery.min.js:6 XHR finished loading: POST "https://pumpdog.me/main/proxy".send @ jquery.min.js:6x.extend.ajax @ jquery.min.js:6Pump.proxyActivity @ pump.js:622Pump.newMinorActivity @ pump.js:587Pump.PersonView.Pump.TemplateView.extend.followProfile @ view.js:1847x.event.dispatch @ jquery.min.js:5v.handle @ jquery.min.js:5
pump.js:212 Error: Internal Server Error
    at Object.$.ajax.error (pump.js:638)
    at c (jquery.min.js:4)
    at Object.p.fireWith (jquery.min.js:4)
    at k (jquery.min.js:6)
    at XMLHttpRequest.r (jquery.min.js:6)
pump.js:218 Internal Server Error

**Comment by h4ck3rm1k3** [comment] 2015-11-03 23:33
following your test account works!

**Comment by iannsp** [comment] 2015-12-24 19:09
I think this is issue is not need anymore. 
I already follow and unfollow this user (and anothers) using the web-client and the pumpa client without any problem.
are u agree in close this issue @h4ck3rm1k3 ?

**Comment by h4ck3rm1k3** [comment] 2015-12-24 19:40
Sure close it.

On Thu, Dec 24, 2015 at 2:09 PM, Ivo Nascimento <notifications@github.com>
wrote:

> I think this is issue is not need anymore.
> I already follow and unfollow this user (and anothers) using the
> web-client and the pumpa client without any problem.
> are u agree in close this issue @h4ck3rm1k3
> <https://github.com/h4ck3rm1k3> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e14n/pump.io/issues/1104#issuecomment-167150622>.
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by strugee** [comment] 2015-12-24 20:43
@h4ck3rm1k3 does that mean you're not still seeing this issue?

**Comment by h4ck3rm1k3** [comment] 2015-12-24 20:51
I am not working on pump right now,

On Thu, Dec 24, 2015 at 3:43 PM, Alex Jordan <notifications@github.com>
wrote:

> @h4ck3rm1k3 <https://github.com/h4ck3rm1k3> does that mean you're not
> still seeing this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e14n/pump.io/issues/1104#issuecomment-167158467>.
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by iannsp** [comment] 2015-12-24 20:58
I start checking old issues in the project and think we can close some of the oldest just asking for their owners feedback, like here.
anyway, I just ask for close because I use this funcionallity from both webclient and pumpa client without any warning and It seems fixed right now.

**Comment by strugee** [comment] 2015-12-25 00:43
Closing since it seems like this isn't an issue anymore.

**Closed by strugee** 2015-12-25 00:43 UTC

**Comment by iannsp** [comment] 2015-12-28 16:21
this issue is related to #1092
